# Generated by Django 4.2.11 on 2024-04-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_cadastro_options_alter_cadastro_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
